### ISSUE TITLE
python3出现报错

### ISSUE THREAD

**Issue by lithromantic** [glzjin/wechat_print_bot#1]
root@raspberrypi:~/wechat_print_bot# python3 buu.py
Traceback (most recent call last):
  File "buu.py", line 5, in <module>
    import buu_msg_handle
  File "/root/wechat_print_bot/buu_msg_handle.py", line 1, in <module>
    import buu_config, buu_command_dict, buu_database
  File "/root/wechat_print_bot/buu_command_dict.py", line 1, in <module>
    import buu_config, buu_database
  File "/root/wechat_print_bot/buu_database.py", line 2, in <module>
    import buu_config, buu_model
  File "/root/wechat_print_bot/buu_model.py", line 4, in <module>
    class class_model(object):
  File "/root/wechat_print_bot/buu_model.py", line 8, in class_model
    host = buu_config.config.mysql_addr, db = buu_config.config.mysql_database)
  File "/usr/local/lib/python3.4/dist-packages/sqlobject/mysql/mysqlconnection.py", line 99, in __init__
    'Cannot find a MySQL driver, tried %s' % drivers)
ImportError: Cannot find a MySQL driver, tried mysqldb

上面的是报错日志，服务器上和树莓派上测试的都是一样的报错，不知道是哪里的问题.

**Comment by glzjin** [comment]
https://m.jb51.net/article/54120.htm

尝试装一下mysql的支持库

**Comment by lithromantic** [comment]
https://raspberrypi.stackexchange.com/questions/78215/how-to-connect-mysqldb-in-python-3
用这个解决了， 但是发现生成的二维码有问题，如下：
![360截图16350910153452.png](https://i.loli.net/2018/05/27/5b0a18681bdb5.png)
谢谢赵大
